### ISSUE TITLE
function anomoly

### ISSUE THREAD

**Issue by ChetHarrison** [ChetHarrison/jsdoccer#10]
from `app-router.yaml`
missing parameter name

``` yaml
  _getController:
    description: | 
      @api private
      @returns {<type>} -
```
